export const SET_MOVIES_LIST = "SET_MOVIES_LIST";
export const RESET_MOVIES_LIST = "RESET_MOVIES_LIST";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const RESET_SEARCH_QUERY = "RESET_SEARCH_QUERY";