export const SET_MOVIES_LIST = "SET_MOVIES_LIST";
export const RESET_MOVIES_LIST = "RESET_MOVIES_LIST";

export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE";
export const RESET_SELECTED_MOVIE = "RESET_SELECTED_MOVIE";